### ISSUE TITLE
MA10, MA20 & M30 - Select Movie from Search Results, Fetch Movie Information & save to localStorage

### ISSUE THREAD

**Issue by daveholst** [busy-boys/movie-master#10]
This Task is going to focus on getting a few things done in regards to building a movie collection that exists on local storage.
I would probably work on this file in `./assets/js/collection.js`

I'm guessing an event handler on the add buttons of each search result. 

- [x] add eventListener to 'add to collection button' (prob do this in the results build loop above the append to contrainer movie.js line-105)
- [x] I think we want to write the imdB number/code in the HTML of the individual search results to be accessed by the eventListener. I would use a custom data attribute: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes. I would just add this to the button (movie.js ln 92)
- [x] write a function(callback) to fire on the 'add to collection' button that can take the data attribute in that you aded before and add that imdb code/id to an array of objects on the localStorage. Probably put the title and year in while you are at it. Call it something like myCollection.

**Finished When:**
WHEN I click +Collection
THEN an array of objects exists on Local Storage containing movies from myCollection.
WHEN I click +Collection again
THEN another movie is added to the array - does not add duplicates. 

I wouldnt worry about getting more information or populating anthing to the DOM. That will be cover in MA20 & MA30.  

Any takers????? 😎

**Comment by daveholst** [comment]
Ritz in collection.js
**Function #1**
- [x] make a function that takes an imdb ID
- [x] builds an object of movie data - title, year, etc. 
- [x] writes that object to the array(if exists) on localStorage @ myCollection

~~**Function #2**~~
~~Takes Local storage and builds mycollection to the DOM.~~
This will be built on the MA40 branch/issue, but still on the collections.js file

**Comment by daveholst** [comment]
OBJECT DATA PROPS:

- Ttile
- Year
- Ratings (imdb, rotten, metacritic)
- Director
- shortPlot
- contentRating
- posterURL
- runtime

**Comment by daveholst** [comment]
@RitzGL I'll format the first item in 'my Collection' to give you a template for the html.

**Comment by daveholst** [comment]
*Code Review* for Commit 75596c7 - successfully reading and storing object from imdb search implementation into localStorage. @RitzGL 

Nice Code 👍 You definitely taught me something about promises! I had always just asumed the callback function required a resolved promise to chain, but the `.then()`method itself also provides a promise so they can be chained after (if only synchronise behaviour is required.) Very Interesting and clean 👏 !!!!  

Overall looks good and should get the job done, just a couple of things to consider (sorry if these are on your todo and I'm stating the obvious):
- [x] It would be good to have the imdbID in the movie selectedFilm object for searching.
- [x] I would consider moving the `let collection` (ln5) to the very start of the getFilmInformation function (and at the start of the next few future funtions. I think having it on the global scope is just adding a middle layer that we have to keep track of ie. making sure everything has the correct values (collection & localStorage) to simplify this it might be worth taking it out of the global scope and doing the following for functions:

```js
function blahBlayYaYa() {
// starts with
let storedCollection = localStorage.getItem('Collection');
storedCollection = JSON.parse(storedCollection)
... do yo thing

// finishes with 
localStorage.setItem('Collection', JSON.stringify(collection))
}
```

so the pattern is get current local data off, work with it, put it back on. 

- [x] with the above collection idea, you can put a conditional checker in the `getFilmInformation` function with an early return at the start of that function to avoid duplicates 


I'm thinking the checker would be something like this it is pretty long winded but easy to read!:
```js
let isDuplicate = false;

for(let i = 0; i < collection.length; i++) {
  if (collection[i].imdbID = imdbID) {
    isDuplicate = true;
    break;  
  }
} 
  
(if isDuplicate === true) {
return
} 
... cont processing function
```

- [x] I agree you need something happening with localStorage  and collections when the file is initialized. I think just a conditional checker here to see if the array exits on LS 
```js
(if localStorage.getItem('Collection') === false) {
// write a blank array in, otherwise push wont work later.
    let collection = [];
    localStorage.setItem('Collection', JSON.stringify(collection));
} 
```
Just some ideas! It is looking good! 😎

**Comment by daveholst** [comment]
@RitzGL ,
I've commited 75596c7 to MA10 with the updated html to be used as movie collection card template.

The center tag is a bit jank! I just used it in the js the other day without realising it was deprecated in HTML4 (showing my age a bit....) 😂 It still works! I tried to do it properly with bulma/css and wasted ~45mins. Feel free to have a try if you can be buggered.

**Comment by RitzGL** [comment]
In `getFilmInformation()` the array keeps getting declared inside as blank, thus not saving the collection into storage; it only saves an array with a single element inside it. 

After testing it, and leaving it outside of the function within global context allows for the array to have elements added to it without it being blank.
