### ISSUE TITLE
CA20 - Remove a selected movie from stage

### ISSUE THREAD

**Issue by daveholst** [busy-boys/movie-master#16]
I think we were originally thinking we would need a delete button down in the stage area to remove a movie. 

On reflection I think this might just add more work and complexity. Instead, we can just set the buttons on the movie collection card to overwrite either the left or the right side of the staging area.

Happy to hear any input on this!

![image](https://user-images.githubusercontent.com/46893433/115104033-8a530f80-9f88-11eb-88e7-8f743c340656.png)

TODO:

- [x] discuss with group
- [x] close this issue as no longer required

**Comment by RitzGL** [comment]
Happy to add delete button on the cards, rather than stage
