### ISSUE TITLE
CL20 & CL30 - Look at Profit Budget

### ISSUE THREAD

**Issue by daveholst** [busy-boys/movie-master#6]
Users should be able to retrieve movie profit / budget information

TODO:

- [x] Find API to get this information. omdb?
- [x] Build basic (async & returns promise) function to retrieve information
- [x] API / Function should return Box Office Profits / Movie Budget
~~- [ ] Event Handler / Trigger~~
~~- [ ] Results should then be pushed to DOM (Stage Cards on add?)~~
Moved to CL50 #15 - Add Information to Stage Card in DOM

**Comment by daveholst** [comment]
Would be good if somebody can start work on a basic fetch function for this (preferablly returning a promise)
I suggest creating a  profit.js file in the `./assets/js/` folder and start trying to get the data back.

Looks like all the info can come from the TMdB api: https://developers.themoviedb.org/3/movies/get-movie-details

If somebody wants to take this on just let us know in here and i'll assign the task to you (if you cant do it yourself)

**Comment by daveholst** [comment]
API KEY: d38648803859bebf97aabe61377bba3c

**Comment by daveholst** [comment]
**CODE REVIEW** Commit 030b491 - Adjusted budget and revenue based on historical CPI @rorylkd 

This looks great and appears to be working well! 

Just a few quick things to consider:

- [x] line 164 if you can get that final object to also include/rename 
- revenue(orignal when movie was shot) 
- budget (original when movie was shot)
- adjust revenue (cpi adjusted)
- adjusted profit(cpi adjusted)
it will just make the data a bit easier to injest on the next stage! And change the property names to lowercase eg`revenue: ...`

- [x] line 169 just change that to `return adjustedFinancials` so we can injest the data with domBuilder. 

and I reckon that will be a wrap for that function!! 🍻

**Comment by rorylkd** [comment]
Great! I'll make the changes as soon as I get home 👍 Thanks

**Comment by daveholst** [comment]
All sorted on this one 👍 . I'm closing it out and moving it to the done pile!
